### ISSUE TITLE
incorrect PEIM files in X64 dir

### ISSUE THREAD

**Issue by Raven19409** [yeggor/UEFI_BinDiff#1]
try to load to IDA "..X64\MdeModule\PeiCore.debug"

**Comment by yeggor** [comment]
Hi, I did not find any errors while loading this file in IDA.

```
debug-efi-elf-modules\X64\MdeModule>file PeiCore.debug
PeiCore.debug: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, with debug_info, not stripped
```

In this case it is a simple ELF 64-bit file with debug info.

```
debug-efi-elf-modules\X64\MdeModule>"C:\Program Files\IDA Pro 7.4\ida64.exe" PeiCore.debug
```

**Comment by Raven19409** [comment]
Да в Иду можно затолкать всё, что угодно. Нужно смотреть на содержимое!
.text:0000000000000B6D ; GUID *__usercall CopyGuid@<rax>(GUID
*DestinationGuid@<rcx>, const GUID *SourceGuid@<rdx>)
.text:0000000000000B6D CopyGuid        proc near
.text:0000000000000B6D DestinationGuid = rcx                   ; GUID *
.text:0000000000000B6D SourceGuid = rdx                        ; const GUID
*
.text:0000000000000B6D                 mov     r8, DestinationGuid
.text:0000000000000B70                 sub     rsp, 28h
.text:0000000000000B74                 mov     DestinationGuid, SourceGuid
; Buffer
.text:0000000000000B77 DestinationGuid = r8                    ; GUID *
.text:0000000000000B77                 call    near ptr
*ReadUnaligned64-93Ch*
.text:0000000000000B7C                 mov     [DestinationGuid], rax
.text:0000000000000B7F                 lea     rcx, [SourceGuid+8] ; Buffer
.text:0000000000000B83                 call    near ptr ReadUnaligned64-948h
.text:0000000000000B88                 mov     [DestinationGuid+8], rax
.text:0000000000000B8C                 mov     rax, DestinationGuid
.text:0000000000000B8F                 add     rsp, 28h
.text:0000000000000B93                 retn
.text:0000000000000B93 CopyGuid        endp
Т.е. Вы считаете что это нормально? (красным я выделил, но внутри очень
много вещей, которые выделяет красным сама ИДА!!!)
Вообще-то UEFI для IA32 означает, что и PEIM и DXE модули делаются для
32-режима.
А X64 в EDKII для Intel означает, что все модули PEIM фазы работают в
32-режиме, а модули DXE фазы - в 64 режиме!

чт, 16 янв. 2020 г. в 19:01, Vasilenko Egor <notifications@github.com>:

**Comment by yeggor** [comment]
Файл `PeiCore.debug` из архива не является модулем PEIM-фазы. Это ELF-файл с отладочными символами, как я и написал выше. При сборке с gcc режиме debug эти файлы создаются рядом с оригинальными и предназначены для загрузки символов в gdb при отладке с исходниками (https://github.com/tianocore/tianocore.github.io/wiki/How-to-debug-OVMF-with-QEMU-using-GDB).

**Comment by Raven19409** [comment]
А зачем 32-разрядному модулю дебаг-символы 64-разрядные? Я не утверждал,
что " файл PeiCore.debug  является модулем PEIM-фазы  ", но  файл "
PeiCore.efi"  является 32-х разрядным модулем  PEIM-фазы.
Может быть, что я не очень внимательно просмотрел материал по Вашей ссылке,
но там идёт речь о 32-х разрядных модулях. Может их (все 32-х разрядные)
просто исключить их X64, тогда и вопросов не будет!
Честно говоря, я не представляю, как отладчик сможет разобраться
одновременно с 32-х и 64-х разрядными символами!!!

вт, 21 янв. 2020 г. в 02:51, Vasilenko Egor <notifications@github.com>:

**Comment by yeggor** [comment]
>> А зачем 32-разрядному модулю дебаг-символы 64-разрядные
>> Честно говоря, я не представляю, как отладчик сможет разобраться
одновременно с 32-х и 64-х разрядными символами!!!

модуль и не будет 32-разрядным, если debug-файл 64-разрядный

>> Может быть, что я не очень внимательно просмотрел материал по Вашей ссылке,
но там идёт речь о 32-х разрядных модулях. Может их (все 32-х разрядные)
просто исключить их X64, тогда и вопросов не будет!

речь идет о 32-разрядных модулях только в качестве примера, на самом деле OvmfPkg можно собрать 3-мя способами:
* IA32 - все модули в 32-битном режиме
* IA32 X64 - только модули фазы PEI в 32-битном режиме
* X64 - все модули в 64-битном режиме (можете проверить: собрать и запустить через `qemu-system-x86_64 -pflash ovmf`)

>> Может их (все 32-х разрядные)
просто исключить их X64, тогда и вопросов не будет!

я могу добавить debug-файлы из ovmf в режиме IA32 X64, но все те же PEI-модули можно сейчас найти в `debug-efi-elf-modules\IA32\Ovmf\`

да, на реальном железе все модули PEI-фазы 32-битные, и вряд ли придется когда-либо реверсить их 64-битные сборки, но все же, пусть будут

**Comment by Raven19409** [comment]
Я просто только что посмотрел PeiCore из Вашей версии тестов для
UEFI_ReTool, там в X64 этот модуль смотрится внешне вполне приемлемо.
То ли в случае данного проекта сказывается, что это ELF, а не PE+, но
внутри IDA он выглядит очень непрезентабельно!
Я в основном об этом толкую. Но, тем не  менее, там что-то некорректно! Что
именно, пока не разобрался!
Мельком просматривал Ваш скрипт, там же для каждого файла будет IDA-база
сформирована!!!
Вполне допускаю, что X64 версия имеет место жить даже для Интела, но в
реальных прошивках ещё не встречал (кроме Ваших примеров).
Правда, вот только что попросил ребят собрать мне такой, сейчас посмотрю.
Кстати, можно не обязательно через GitHub разбираться! Как будет удобно!

вт, 21 янв. 2020 г. в 13:02, Vasilenko Egor <notifications@github.com>:

**Comment by yeggor** [comment]
напишите на почту

>> То ли в случае данного проекта сказывается, что это ELF, а не PE+, но
внутри IDA он выглядит очень непрезентабельно!

там есть небольшое несоответствие в операндах, отсюда и такие непонятные вызовы по отрицательным смещениям. тем не менее, все символы на месте, а большего от debug-модулей и не требуется

вот пример:
.efi
```
.text:000000000000641B                               loc_641B:                               ; CODE XREF: _ModuleEntryPoint+7E↑j
.text:000000000000641B 8A 44 24 1F                                   mov     al, [rsp+78h+var_59]
.text:000000000000641F 49 89 9E 10 02 00 00                          mov     [r14+210h], rbx
.text:0000000000006426 48 83 EC 20                                   sub     rsp, 20h
.text:000000000000642A BA 30 00 00 00                                mov     edx, 30h ; '0'
.text:000000000000642F B9 02 00 00 00                                mov     ecx, 2
.text:0000000000006434 41 88 86 18 02 00 00                          mov     [r14+218h], al
.text:000000000000643B E8 A1 B7 FF FF                                call    sub_1BE1
.text:0000000000006440 48 83 C4 20                                   add     rsp, 20h
.text:0000000000006444 48 89 C6                                      mov     rsi, rax
.text:0000000000006447 48 85 C0                                      test    rax, rax
.text:000000000000644A 74 35                                         jz      short loc_6481
.text:000000000000644C 48 83 EC 20                                   sub     rsp, 20h
.text:0000000000006450 48 8D 48 08                                   lea     rcx, [rax+8]
.text:0000000000006454 48 8D 15 55 07 00 00                          lea     rdx, EFI_HOB_MEMORY_ALLOC_STACK_GUID_0x6bb0
.text:000000000000645B E8 0D A7 FF FF                                call    sub_B6D
.text:0000000000006460 BA 04 00 00 00                                mov     edx, 4
.text:0000000000006465 C7 46 28 04 00 00 00                          mov     dword ptr [rsi+28h], 4
.text:000000000000646C 48 8D 4E 2C                                   lea     rcx, [rsi+2Ch]
.text:0000000000006470 4C 89 6E 18                                   mov     [rsi+18h], r13
.text:0000000000006474 4C 89 66 20                                   mov     [rsi+20h], r12
.text:0000000000006478 E8 2E AA FF FF                                call    sub_EAB
.text:000000000000647D 48 83 C4 20                                   add     rsp, 20h
```

.debug
```
.text:000000000000641B                               loc_641B:                               ; CODE XREF: PeiCheckAndSwitchStack+72↑j
.text:000000000000641B                               StackOffset = rbx                       ; UINTN
.text:000000000000641B 8A 44 24 1F                                   mov     al, [rsp+78h+StackOffsetPositive]
.text:000000000000641F 49 89 9E 10 02 00 00                          mov     [r14+210h], StackOffset
.text:0000000000006426 48 83 EC 20                                   sub     rsp, 20h
.text:000000000000642A BA 30 00 00 00                                mov     edx, 30h ; '0'
.text:000000000000642F B9 02 00 00 00                                mov     ecx, 2          ; Buffer
.text:0000000000006434 41 88 86 18 02 00 00                          mov     [r14+218h], al
.text:000000000000643B E8 42 6F FF FF                                call    near ptr ReadUnaligned64-2EBEh
.text:0000000000006440 48 83 C4 20                                   add     rsp, 20h
.text:0000000000006444 48 89 C6                                      mov     rsi, rax
.text:0000000000006447 48 85 C0                                      test    rax, rax
.text:000000000000644A 74 35                                         jz      short loc_6481
.text:000000000000644C 48 83 EC 20                                   sub     rsp, 20h
.text:0000000000006450 48 8D 48 08                                   lea     rcx, [rax+8]    ; Buffer
.text:0000000000006454 48 8D 15 AA 0E 00 00                          lea     rdx, gEfiPeiSecurity2PpiGuid+0B85h
.text:000000000000645B E8 1A 4E FF FF                                call    near ptr ReadUnaligned64-4FC6h
.text:0000000000006460 BA 04 00 00 00                                mov     edx, 4
.text:0000000000006465 C7 46 28 04 00 00 00                          mov     dword ptr [rsi+28h], 4
.text:000000000000646C 48 8D 4E 2C                                   lea     rcx, [rsi+2Ch]  ; Buffer
.text:0000000000006470 4C 89 6E 18                                   mov     [rsi+18h], r13
.text:0000000000006474 4C 89 66 20                                   mov     [rsi+20h], NewStackSize
.text:0000000000006478 E8 5C 54 FF FF                                call    near ptr ReadUnaligned64-4967h
.text:000000000000647D 48 83 C4 20                                   add     rsp, 20h
```

**Comment by Raven19409** [comment]
Разобрался с вопросом. Я был не прав. До этого имел дело только с
"традиционными" вариантами  IA32 и IA32 X64.
В X64 действительно находятся модули PEIM 64-х разрядные и это правильно.
Вы правы, оба варианта/каталога (IA32 и X64) полностью корректны.
Было бы проще (и понятней изначально), если бы кроме debug-модулей были бы
приведены их PE варианты
(лучше, если не по отдельности, а в виде готовой прошивки) - это просто моё
личное мнение, если что!
Меня сильно смутило то, что Вы выше назвали "...там есть небольшое
несоответствие в операндах".
Я, кажется знаю, откуда тут ноги растут, но пока озвучивать не стоит -
проверить нужно!
Вопрос можно считать закрытым, но всё-таки, может добавить полученные
прошивки, соответствующие приведённым debug-модулям?.

вт, 21 янв. 2020 г. в 16:17, Vasilenko Egor <notifications@github.com>:
